import Head from 'next/head'


import { Inter } from '@next/font/google'
import Top from './top'
import { useEffect, useState } from 'react';
import { setIsMobile, utilState } from '../reducers/util';
import { useAppDispatch, useAppSelector } from '../app/hooks';
import { 
  UtilState,
  utilState as originUtilState
} from "../reducers/util";
import { isMobile } from '../helpers/util';

const inter = Inter({
    variable: '--inter-font',
  })

export default function Layout(props:any)
{
  const dispatch                      = useAppDispatch();
  const utilState:UtilState           = useAppSelector(originUtilState);
  const [ready, setReady]             = useState<boolean>(false);

  const resizeHandle = () => {
    checkIsMobile();
  }

  const checkIsMobile = () => {
    dispatch(setIsMobile(isMobile()));
  }

  useEffect(() => {
    if(utilState.isMobile != undefined) setReady(true);
  }, [utilState.isMobile]);

  useEffect(() => {
    checkIsMobile();
    window.addEventListener('resize', resizeHandle);
    return () => {
      window.removeEventListener('resize', resizeHandle);
    };
}, []);

  return (
      <>
        <Head>
          <title>Hei Yeung:Web Developer</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icos/favicon.ico" />
        </Head>
        {ready &&
          <>
          <Top />
          <main 
            className={`z-[10] ${inter.variable} mt-[106px] desktop:mt-[148px]`}
          >
            {props.children}
            <div 
                className={`waves-bg-mobile desktop:waves-bg`}
            />
          </main>
          </>
        }
      </>
    )
}