import Head from 'next/head'


import { Inter } from '@next/font/google'
import Top from './top'
const inter = Inter({
    variable: '--inter-font',
  })

export default function Layout(props:any)
{



    return (
        <>
          <Head>
            <title>Hei Yeung:Web Developer</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/icos/favicon.ico" />
          </Head>
          <Top />
          <main 
            className={`z-[10] ${inter.variable} mt-[106px] desktop:mt-[148px]`}
          >
            {props.children}
            <div 
                className={`waves-bg-mobile desktop:waves-bg`}
            />
          </main>
        </>
      )
}